name = "spin-macho-casino-es"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spin-macho-casino.es"
HMAC_KEY = "eb1ba7407da8e1ff79ccdf47530c4bdcff477bff290cfcb9c4da1af06fb108db"
COOKIE_NAME = "2vg"
PLAY_PATH = "start-now"
BUTTON_ID = "p95c2f39920c8867f4e0b73c97fd6510b"
GATE_SALT = "098df60d16684f63"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "9qyk"
CTA_SELECTOR = ".play-button"
